# Generated by Django 5.2.1 on 2025-05-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_shop_image_shopitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='user',
        ),
    ]
