# Generated by Django 5.2.1 on 2025-05-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_shopitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
