# Generated by Django 5.2.1 on 2025-05-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_shopitem_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='date_added',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_items', to='application.shop'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='application.shop'),
        ),
    ]
